version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ./rabbitmq:/etc/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: userRabbitmq
            RABBITMQ_DEFAULT_PASS: oq3TdgCyDb7qyKB
            RABBITMQ_ERLANG_COOKIE: '6cb84771-0a30-4982-b6c2-0e19648c5063'
        command: >
            sh -c "
            rabbitmq-plugins enable rabbitmq_management;
            rabbitmq-server;
            "

    setup:
        image: rabbitmq:3-management
        depends_on:
            - rabbitmq
        volumes:
            - ./setup.sh:/setup.sh
        entrypoint: ['/bin/bash', '/setup.sh']

    postgres:
        image: postgres:13
        container_name: postgres
        environment:
            POSTGRES_USER: userPostgres
            POSTGRES_PASSWORD: 5G5SSnyXI0Q
            POSTGRES_DB: teachChallange
        ports:
            - '5432:5432'
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '8080:80'
        depends_on:
            - postgres
