name: challenge

services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 2s
      start_interval: 5s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s

  postgres:
      image: postgres:16-alpine
      ports:
        - 5432:5432
      expose:
        - 5432
      volumes:
        - db-data:/var/lib/postgresql/data
        - ./migrations:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_PASSWORD: dbsecret
        POSTGRES_USER: dbuser
        POSTGRES_DB: payables_db
      restart: always
      healthcheck:
        test: ["CMD", "pg_isready", "--username=dbuser", "--dbname=payables_db"]
        interval: 1m30s
        timeout: 5s
        retries: 5
        start_period: 5s
        start_interval: 5s

  webserver:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/payables
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:$WEB_SERVER_PORT/healthcheck || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s

  haproxy:
    build: ./haproxy
    ports:
      - 8181:8181
      - 8100:8100
    depends_on:
      webserver:
        condition: service_healthy

volumes:
  db-data:
  rabbitmq-data:
