version: '3.5'

services:
  m01: &api
    hostname: m01
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
        - db
    environment:
      - PORT=8080
      - DATABASE_DATABASE=financial
      - DATABASE_DIALECT=postgres
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres

  m02:
    <<: *api
    hostname: m02
    ports:
      - "8082:8080"
    environment:
      - PORT=8080

  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - m01
      - m02
    ports:
      - "9999:9999"
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financial
    command: "postgres -c max_connections=20 -c listen_addresses='*' -c effective_io_concurrency=2 -c autovacuum=on"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    name: financial-nginx
