version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_USER=pguser
      - POSTGRES_DB=chalenge_db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - '5672'
      - '15672'
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/rabbitmq/log/:/var/log/rabbitmq\
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 30s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    command: ['npm', 'run', 'start:prod']
    ports:
      - 3000:3000
    env_file:
      - .env.build
    restart: always
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - api
    command: ['npm', 'run', 'start:consumer:prod']
    env_file:
      - .env.build
    restart: always
