name: tech-challenge-ecosystem

services:
    api:
        container_name: tech-ecosystem
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 3000:3000
        env_file:
            - .env.docker
        restart: always
    db:
        container_name: postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=tech-ecosystem
        volumes:
            - ~/postgres:/var/lib/postgresql/data
