export const TRANSACTION_CONTROLLER = 'TRANSACTION_CONTROLLER';
export const PAYABLE_CONTROLLER = 'PAYABLE_CONTROLLER';
export const PAYABLE_REPOSITORY = 'PAYABLE_REPOSITORY';
export const DATA_SOURCE = 'DATA_SOURCE';
